-- structured_problems 테이블 생성 (problem_type 컬럼 제거)
create table public.structured_problems (
  id uuid not null default gen_random_uuid (),
  idx bigint generated by default as identity not null,
  lang text not null,
  category text not null,
  topic text[] null,
  difficulty text not null,
  time_limit text null,
  target_template_code text not null,
  created_by text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  active boolean not null default true,
  user_view_layer jsonb not null,
  system_view_layer jsonb not null,
  evaluation_layer jsonb not null,
  constraint structured_problems_pkey primary key (id),
  constraint structured_problems_idx_unique unique (idx)
) TABLESPACE pg_default;

