# Streamlit secrets configuration
# Add your API keys here for local development
# OPENAI_API_KEY=your_openai_api_key_here
# EDGE_FUNCTION_URL=your_edge_function_url_here
# EDGE_SHARED_TOKEN=your_edge_shared_token_here
# SUPABASE_URL=your_supabase_url_here
# SUPABASE_ANON_KEY=your_supabase_anon_key_here
# GEMINI_API_KEY=your_gemini_api_key_here